normal_standard_weapons = {
    "_type": "normal_standard_weapons",
    "Рогатка": {
        "_id": 1,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239103",
    },
    "Клятва стрелка": {
        "_id": 2,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239098",
    },
    "Лук ворона": {
        "_id": 3,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239093",
    },
    "Меч небесного всадника": {
        "_id": 4,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239266",
    },
    "Предвестник зари": {
        "_id": 5,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239269",
    },
    "Холодное лезвие": {
        "_id": 6,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239264",
    },
    "Дубина переговоров": {
        "_id": 7,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239088",
    },
    "Меч драконьей крови": {
        "_id": 8,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239268",
    },
    "Металлическая тень": {
        "_id": 9,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239270",
    },
    "Чёрная кисть": {
        "_id": 10,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239100",
    },
    "Изумрудный шар": {
        "_id": 11,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239101",
    },
    "Руководство по магии": {
        "_id": 12,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239102",
    },
    "Эпос о драконоборцах": {
        "_id": 13,
        "type": "weapon",
        "rarity": 3,
        "picture": "photo-193964161_457239099",
    },
}

rare_standard_weapons = {
    "_type": "rare_standard_weapons",
    "Бесструнный": {
        "_id": 1,
        "type": "weapon",
        "rarity": 4,
        "picture": "photo-193964161_457239265",
    },
    "Боевой лук Феврония": {"_id": 2, "type": "weapon", "rarity": 4, "picture": ""},
    "Ржавый лук": {"_id": 3, "type": "weapon", "rarity": 4, "picture": ""},
    "Церемониальный лук": {"_id": 1, "type": "weapon", "rarity": 4, "picture": ""},
    "Драконий рык": {"_id": 4, "type": "weapon", "rarity": 4, "picture": ""},
    "Меч-флейта": {"_id": 5, "type": "weapon", "rarity": 4, "picture": ""},
    "Меч Феврония": {"_id": 6, "type": "weapon", "rarity": 4, "picture": ""},
    "Церемониальный меч": {"_id": 7, "type": "weapon", "rarity": 4, "picture": ""},
    "Дождерез": {"_id": 8, "type": "weapon", "rarity": 4, "picture": ""},
    "Двуручный меч Феврония": {
        "_id": 9,
        "type": "weapon",
        "rarity": 4,
        "picture": "photo-193964161_457239046",
    },
    "Меч-колокол": {"_id": 10, "type": "weapon", "rarity": 4, "picture": ""},
    "Церемониальный двуручный меч": {
        "_id": 11,
        "type": "weapon",
        "rarity": 4,
        "picture": "",
    },
    "Гроза драконов": {"_id": 12, "type": "weapon", "rarity": 4, "picture": ""},
    "Копьё Феврония": {"_id": 13, "type": "weapon", "rarity": 4, "picture": ""},
    "Кодекс Феврония": {"_id": 14, "type": "weapon", "rarity": 4, "picture": ""},
    "Око сознания": {"_id": 15, "type": "weapon", "rarity": 4, "picture": ""},
    "Песнь странника": {
        "_id": 16,
        "type": "weapon",
        "rarity": 4,
        "picture": "photo-193964161_457239028",
    },
    "Церемониальные мемуары": {"_id": 17, "type": "weapon", "rarity": 4, "picture": ""},
}

legendary_standard_weapons = {
    "_type": "legendary_standard_weapons",
    "Лук Амоса": {
        "_id": 1,
        "type": "weapon",
        "rarity": 5,
        "picture": "photo-193964161_457239024",
    },
    "Небесное крыло": {
        "_id": 2,
        "type": "weapon",
        "rarity": 5,
        "picture": "photo-193964161_457239106",
    },
    "Меч Сокола": {"_id": 3, "type": "weapon", "rarity": 5, "picture": ""},
    "Небесный меч": {"_id": 4, "type": "weapon", "rarity": 5, "picture": ""},
    "Волчья погибель": {
        "_id": 5,
        "type": "weapon",
        "rarity": 5,
        "picture": "photo-193964161_457239023",
    },
    "Небесное величие": {"_id": 6, "type": "weapon", "rarity": 5, "picture": ""},
    "Нефритовый коршун": {"_id": 7, "type": "weapon", "rarity": 5, "picture": ""},
    "Небесная ось": {
        "_id": 8,
        "type": "weapon",
        "rarity": 5,
        "picture": "photo-193964161_457239109",
    },
    "Молитва святым ветрам": {"_id": 9, "type": "weapon", "rarity": 5, "picture": ""},
    "Небесный атлас": {"_id": 10, "type": "weapon", "rarity": 5, "picture": ""},
}

rare_standard_characters = {
    "_type": "rare_standard_characters",
    "Барбара": {
        "_id": 1,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239273",
        "not_in_banner": False,
    },
    "Беннет": {
        "_id": 2,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239104",
        "not_in_banner": False,
    },
    "Бэй Доу": {
        "_id": 3,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239275",
        "not_in_banner": False,
    },
    "Горо": {
        "_id": 4,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239271",
        "not_in_banner": False,
    },
    "Диона": {
        "_id": 5,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Кэйа": {
        "_id": 6,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": True,
    },
    "Лиза": {
        "_id": 7,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239107",
        "not_in_banner": True,
    },
    "Нин Гуан": {
        "_id": 8,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239032",
        "not_in_banner": False,
    },
    "Ноэлль": {
        "_id": 9,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239033",
        "not_in_banner": False,
    },
    "Розария": {
        "_id": 10,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239025",
        "not_in_banner": False,
    },
    "Рейзор": {
        "_id": 11,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Сара": {
        "_id": 12,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Сахароза": {
        "_id": 13,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Саю": {
        "_id": 14,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Син Цю": {
        "_id": 15,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Синь Янь": {
        "_id": 16,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Сян Лин": {
        "_id": 17,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Тома": {
        "_id": 18,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Фишль": {
        "_id": 19,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239031",
        "not_in_banner": False,
    },
    "Чун Юнь": {
        "_id": 20,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239274",
        "not_in_banner": False,
    },
    "Эмбер": {
        "_id": 21,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": True,
    },
    "Юнь Цзинь": {
        "_id": 22,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Янь Фей": {
        "_id": 23,
        "type": "character",
        "rarity": 4,
        "picture": "",
        "not_in_banner": False,
    },
    "Куки Синобу": {
        "_id": 24,
        "type": "character",
        "rarity": 4,
        "picture": "photo-193964161_457239272",
        "not_in_banner": False,
    }
}

legendary_standard_characters = {
    "_type": "legendary_standard_characters",
    "Кэ Цин": {
        "_id": 1,
        "type": "character",
        "rarity": 5,
        "picture": "photo-193964161_457239050",
    },
    "Джинн": {
        "_id": 2,
        "type": "character",
        "rarity": 5,
        "picture": "photo-193964161_457239085",
    },
    "Дилюк": {"_id": 3, "type": "character", "rarity": 5, "picture": ""},
    "Мона": {"_id": 4, "type": "character", "rarity": 5, "picture": ""},
    "Ци Ци": {
        "_id": 5,
        "type": "character",
        "rarity": 5,
        "picture": "photo-193964161_457239278",
    },
}

legendary_event_characters = {
    "_type": "legendary_event_characters",
    "Ху Тао": {
        "_id": 1,
        "type": "character",
        "rarity": 5,
        "picture": "photo-193964161_457239045",
        "event": "moment_of_bloom",
    },
    "Кэ Цин": {
        "_id": 2,
        "type": "character",
        "rarity": 5,
        "picture": "photo-193964161_457239050",
        "event": "dance_of_lanterns",
    },
    "Ёимия": {
        "_id": 3,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "tapestry_of_golden_flames",
    },
    "Альбедо": {
        "_id": 4,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "secretum_secretorum",
    },
    "Аяка": {
        "_id": 5,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "the_herons_court",
    },
    "Венти": {
        "_id": 6,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "ballad_in_goblets",
    },
    "Гань Юй": {
        "_id": 7,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "adrift_in_the_harbor",
    },
    "Итто": {
        "_id": 8,
        "type": "character",
        "rarity": 5,
        "picture": "photo-193964161_457239277",
        "event": "onis_royale",
    },
    "Кадзуха": {
        "_id": 9,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "leaves_in_the_wind",
    },
    "Кли": {
        "_id": 10,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "sparkling_steps",
    },
    "Кокоми": {
        "_id": 11,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "drifting_luminescence",
    },
    "Райдэн": {
        "_id": 12,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "reign_of_serenity",
    },
    "Сяо": {
        "_id": 13,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "invitation_to_mundane_life",
    },
    "Тарталья": {
        "_id": 14,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "farewell_of_snezhnaya",
    },
    "Чжун Ли": {
        "_id": 15,

        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "gentry_of_hermitage",
    },
    "Шэнь Хэ": {
        "_id": 16,
        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "the_transcendent_one_returns",
    },
    "Эола": {
        "_id": 17,

        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "born_of_ocean_swell",
    },
    "Яэ Мико": {
        "_id": 18,

        "type": "character",
        "rarity": 5,
        "picture": "",
        "event": "everbloom_violet",

    },
    "Паймон": {
        "_id": 19,
        "type": "character",
        "rarity": 6,
        "picture": "photo-193964161_457239247",
        "event": "emergency_food",
    },
}